server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true